### ISSUE TITLE
[Bug] 1.20.6 Failed to decode packet

### ISSUE THREAD

**Issue by F3F5** [Bram1903/MinecraftPlayerCrasher#10]
![Screenshot_1](https://github.com/Bram1903/MinecraftPlayerCrasher/assets/108226177/9397bc5d-4c44-4326-8eb4-8a3021484494)
just /crash player_name

**Comment by F3F5** [comment]
packetevents latest devbuild idk

**Comment by F3F5** [comment]
interesting [09:03:23 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] No data was sent for dimension Compound{{name=String(minecraft:overworld), id=Int(0)}} to MichaelKozlov

**Comment by Bram1903** [comment]
Yeah, 1.20.5/6 support hasn't been officially released. Yesterday they already patched a few issues with some wrappers, but I'll see if this is an wrapper issue as well. They are working their ass of to support 1.20.5/6 as soon as possible so it can't take much longer.

**Comment by F3F5** [comment]
fixed

**Comment by Bram1903** [comment]
Fixed in: retrooper/packetevents#742
