### ISSUE TITLE
[Question] Plugin isn't showing any return value when typing /crash

### ISSUE THREAD

**Issue by F3F5** [Bram1903/MinecraftPlayerCrasher#12]
I don't see anything in the console when I try to /crash playername
(no crashes, no messages seen)

**Comment by Bram1903** [comment]
Hey @F3F5, 

First of all, the plugin has never been "broken" before. Mostly a specific method wasn't working on some versions. Are you sure both PE and PlayerCrasher are enabled when typing `/plugins` in-game?

Regards,
Bram

**Comment by F3F5** [comment]
> Hey @F3F5,
> 
> First of all, the plugin has never been "broken" before. Mostly a specific method wasn't working on some versions. Are you sure both PE and PlayerCrasher are enabled when typing `/plugins` in-game?
> 
> Regards, Bram
![Screenshot_27](https://github.com/Bram1903/MinecraftPlayerCrasher/assets/170719238/a3276ef4-fb18-44a7-b15f-b19809779341)


I rarely use this plugin, so I only noticed it now
version 2.5.0

**Comment by F3F5** [comment]
sent the same command to the console - no response.

**Comment by Bram1903** [comment]
> sent the same command to the console - no response. 

I am going to look into this. Is the command working fine in game? 

I am currently almost finished with a major release of my AntiHealthIndicator, so once that's done I am planning on basically rewriting this entire plugin so it also works on a proxy as that currently brings issues.

**Comment by F3F5** [comment]
> > sent the same command to the console - no response.
> 
> I am going to look into this. Is the command working fine in game?
> 
> I am currently almost finished 
yes

**Comment by Bram1903** [comment]
This has been fixed in recent commits and will be available in the next release.

**Comment by F3F5** [comment]
As it turns out, it doesn't respond on the other hosting, but it does on the other hosting.
but other plugins work fine.

**Comment by F3F5** [comment]
crash
[15:26:22 INFO]: Usage: /crash <player> [method] 
I can only see this, but try to crash the player - nothing responds

**Comment by Bram1903** [comment]
> As it turns out, it doesn't respond on the other hosting, but it does on the other hosting.
> 
> but other plugins work fine.

I must admit that I have no idea how that could occur. I tested this on multiple platforms and versions (Bukkit, SpigotMC, Paper, Folia, BungeeCord, and Velocity. It doesn't even make sense that it wouldn't work as it's being sent to the console itself. What's the platform and version you are experiencing the issue on, or are they the same across your host?

**Comment by F3F5** [comment]
i'm testing it with https://mgr.hosting-minecraft.pro/ (test server) dionysus 1.12.2 and jdk 17

**Comment by F3F5** [comment]
![Screenshot_18](https://github.com/Bram1903/MinecraftPlayerCrasher/assets/170719238/2b15db5a-a774-4c8c-8d0d-bc559cd11b29)
and now there's no colour after your changes. 
and the console still doesn't work

**Comment by F3F5** [comment]
trying to use " crash MichaelKozlov "

**Comment by F3F5** [comment]
fixed
