### ISSUE TITLE
[Bug] Cancel player keepAlive packet if crash failed

### ISSUE THREAD

**Issue by HaHaWTH** [Bram1903/MinecraftPlayerCrasher#14]
As the title said, when some players are using hack clients with AntiCrash feature, MinecraftPlayerCrasher cannot crash them. Then we can cancel sending/receiving their keepAlive packets to make a **NETWORK PROBLEM**

**Comment by Bram1903** [comment]
Hello,

I am currently in the middle of rewriting this plugin. I'll see how I can solve/fix this in the rewrite!

Kind regards,
Bram

**Comment by Bram1903** [comment]
Hey @HaHaWTH,

I am quite confident I fixed this issue in the latest commit: https://github.com/Bram1903/MinecraftPlayerCrasher/actions/runs/9596811593/artifacts/1620480443

Could you give it a shot, and tell me if this fixes the issue? The provided build is a snapshot of the upcoming release that introduces support for proxy platforms, etc. It has been completely rewritten. 

Kind regards,
Bram

**Comment by HaHaWTH** [comment]
> Hey @HaHaWTH,
> 
> I am quite confident I fixed this issue in the latest commit: https://github.com/Bram1903/MinecraftPlayerCrasher/actions/runs/9599821241/artifacts/1621260987
> 
> Could you give it a shot, and tell me if this fixes the issue? The provided build is a snapshot of the upcoming release that introduces support for proxy platforms, etc. It has been completely rewritten.
> 
> Kind regards, Bram

Ah, in my tests it's getting fixed :)

**Comment by Bram1903** [comment]
Good to hear! This version will be released together with 1.21 support!

**Comment by Bram1903** [comment]
As described in the message above, this should now be fixed
