### ISSUE TITLE
Crash Bypass

### ISSUE THREAD

**Issue by F3F5** [Bram1903/MinecraftPlayerCrasher#5]
https://github.com/Pan4ur/ThunderHack-Recode/pull/270
The player decided to make a bypass of crash, he is a server spammer - I have crash him before.

**Comment by Bram1903** [comment]
Hello again,

6b74bda35bb3d8c2cf58b950d27de420ea04b32c

I just patched the bypass. I will create a new release later today! 

Kind regards,
Bram

**Comment by F3F5** [comment]
oh nice, i can build without problem.

**Comment by Bram1903** [comment]
> oh nice, i can build without problem.

Keep in mind that the current code base uses the latest PacketEvents version, which doesn't yet have the latest commits included (The via version bug for example). I will create a release later today that is based on the latest PacketEvents build.

Once PacketEvents creates a new release I will create an actual release for this project as well.

**Comment by F3F5** [comment]
> > oh nice, i can build without problem.
> 
> Keep in mind that the current code base uses the latest PacketEvents version, which doesn't yet have the latest commits included (The via version bug for example). I will create a release later today that is based on the latest PacketEvents build.
> 
> Once PacketEvents creates a new release I will create an actual release for this project as well.

I'm not a beginner, but thanks

**Comment by Bram1903** [comment]
Fixed in the latest release.
