### ISSUE TITLE
[Bug] Proxy crash when trying to "crash" bedrock player

### ISSUE THREAD

**Issue by cupang-afk** [Bram1903/MinecraftPlayerCrasher#7]
using Geyser and Floodgate plugin on Waterfall proxy (Floodgate also installed on the server)

crash command run fine, the player is kicked but proxy crashed, and cpu usage goes high as it can be until the proxy is killed with SIGKILL

the last log i get from waterfall is
```log
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "logger replace daemon"
```

server version
```log
> version
[15:55:51 INFO]: Checking version, please wait...
[15:55:51 INFO]: Current: git-Purpur-2172 (MC: 1.20.4)*
Previous: git-Purpur-2171 (MC: 1.20.4)
* You are running the latest version
```

waterfall version
```log
> bungee
[15:56:49 INFO]: CONSOLE executed command: /bungee
[15:56:49 INFO]: This server is running Waterfall version git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:da6aaf6:572 by md_5
```

plugin version is 2.2.0

**Comment by Bram1903** [comment]
Hey there, 

I am not sure how this can happen, but I will look into it later this week. Perhaps the packet is going over the proxy which can't handle the packet, and therefore crashes, but that doesn't make much sense! 

Kind regards,
Bram

**Comment by Bram1903** [comment]
Velocity support has been added in recent commits. The next release will include proxy support, and solve this issue!

**Comment by Bram1903** [comment]
Hey @cupang-afk,

Bungeecord (Waterfall) support has been added in recent commits. This means that the plugin can be ran from the proxy itself. I am not sure whether this will solve the proxy from crashing when attempting to crash a bedrock player, but chances are pretty high it has now been fixed. 

Could you give the latest snapshot a try, and give me some feedback? If bedrock issues are still forming an issues I will look into a solution to solve that, as it is now much easier for me to test stuff on the proxy level. 

The snapshot build can be found here: https://github.com/Bram1903/MinecraftPlayerCrasher/actions/runs/9596995167/artifacts/1620529388

Thanks in advance!

Kind regards,
Bram

**Comment by Bram1903** [comment]
It should be fixed, and since this issue has been stalled for a month, I will close it.
