### ISSUE TITLE
Kyori NoClassDefFoundError

### ISSUE THREAD

**Issue by F3F5** [Bram1903/MinecraftPlayerCrasher#9]
https://pastebin.com/2BfwkmZD
https://github.com/Bram1903/MinecraftPlayerCrasher/releases/tag/v2.3.0

**Comment by Bram1903** [comment]
Shit, thanks for reporting! I'll take a look at this!

**Comment by Bram1903** [comment]
https://github.com/Bram1903/MinecraftPlayerCrasher/releases/tag/v2.3.1
